name: Auto Bot
 
on:
  push:
    paths:
      - 'Records/Auto.txt'
      - '.github/workflows/Auto.yml'
  workflow_dispatch:
env:
  GitHubMail: "nopenope22111@gmail.com"
  GitHubName: "ioscdn"
 
jobs:
  Auto_X:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
      - name: Setup Py3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9.12'
      - name: Gather repo
        run: |
          git clone "https://${{ secrets.GH_TOK }}@github.com/user/repo" bot || exit 1
      - name: Build wheels
        timeout-minutes: 330
        continue-on-error: true
        run: |
          cd bot
          bash run
      - name: Quality Control
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY} lupo
          cd lupo || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > Records/Auto.txt
          git add .
          git commit -m "Building [$(date -u +%D-%T%P)]"
          git push -q "https://${{ secrets.GH_TOK }}@github.com/${GITHUB_REPOSITORY}" HEAD:main || exit 1
