name: Auto Bot
 
on:
  push:
    paths:
      - 'Records/Auto.txt'
      - '.github/workflows/Auto.yml'
  workflow_dispatch:
env:
  GitHubMail: "nopenope22111@gmail.com"
  GitHubName: "ioscdn"
 
jobs:
  Auto_X:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
         
      - name: Gather repo
        run: |
          git clone "https://${{ secrets.GH_TOKEN }}@github.com/ioscdn/mirrorui" bot || exit 1
      
      - name: Build wheels
        timeout-minutes: 330
        continue-on-error: true
        run: |
          cd bot
          npm run build
          npm start
      
      - name: Quality Control
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY} lupo
          cd lupo || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > Records/Auto.txt
          git add .
          git commit -m "Building [$(date -u +%D-%T%P)]"
          git push -q "https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}" HEAD:main || exit 1
